version: 1
disable_existing_loggers: false

# フォーマッター定義
formatters:
  standard:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
  detailed:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(module)s:%(lineno)d - %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"

# ハンドラー定義
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: standard
    stream: ext://sys.stdout

  file:
    class: logging.handlers.TimedRotatingFileHandler
    level: DEBUG
    formatter: detailed
    filename: output/logs/quick_api.log
    when: midnight
    interval: 1
    backupCount: 30
    encoding: utf8

  error_file:
    class: logging.handlers.TimedRotatingFileHandler
    level: ERROR
    formatter: detailed
    filename: output/logs/quick_api_error.log
    when: midnight
    interval: 1
    backupCount: 30
    encoding: utf8
    
# ロガー定義
loggers:
  app:  # アプリケーション全体のロガー
    level: INFO
    handlers: [console, file, error_file]
    propagate: false

  app.api:  # API関連のロガー
    level: DEBUG
    handlers: [file, error_file]
    propagate: false

  app.core:  # コア機能のロガー
    level: INFO
    handlers: [console, file]
    propagate: false

# ルートロガー
root:
  level: WARNING
  handlers: [console, error_file]