kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: aks-api-server-role
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete