apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-server
  namespace: openapi-server
  labels:
    app: api-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-server
  template:
    metadata:
      labels:
        app: api-server
    spec:
      serviceAccountName: batch-job-creator  # この行を追加
      containers:
      - name: api-server
        image: api-server-dev:v2.0
        imagePullPolicy: Never
        ports:
        - containerPort: 10081
          name: http
        volumeMounts:
        - name: config-volume
          mountPath: /usr/src/app/app/serverconf.ini
          subPath: serverconf.ini
      volumes:
      - name: config-volume
        configMap:
          name: api-server-config