# configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: api-server-config
  namespace: openapi-server
data:
  serverconf.ini: |
    [server]
    specs = [api.v1]
    api_specification_dir = ./spec
    enable_debugger = true
    enable_swagger_ui = true

    [local-testing]
    local_test_host = 0.0.0.0
    local_test_port = 10081