# k8s-config.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: openapi-app
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: batch-job-creator
  namespace: openapi-server
---
# クラスター全体で一つのClusterRole定義
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: job-manager
rules:
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["create", "get", "list", "watch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: job-creator-binding
  namespace: openapi-app
subjects:
- kind: ServiceAccount
  name: batch-job-creator
  namespace: openapi-server
roleRef:
  kind: ClusterRole
  name: job-manager
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azurefilesinputclaim
  namespace: openapi-app
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: hostpath # ローカルk8sの場合はデフォルトのStorageClassを使用
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azurefilesoutputclaim
  namespace: openapi-app
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: hostpath # ローカルk8sの場合はデフォルトのStorageClassを使用