# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: api-server
  namespace: openapi-server
  labels:
    app: api-server
spec:
  type: NodePort
  ports:
  - port: 10081
    targetPort: 10081
    nodePort: 30081
    name: http
  selector:
    app: api-server