apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azurefilesinputclaim
  namespace: openapi-app
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: hostpath
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azurefilesoutputclaim
  namespace: openapi-app
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: hostpath